### ISSUE TITLE
Doc link broken in readme

### ISSUE THREAD

**Issue by joprice** [janestreet/bin_prot#10]
The documentation link in the readme points to http://mmottl.bitbucket.org/projects/bin_prot/api/, which does not exist.

**Comment by rleonid** [comment]
Ping.

**Comment by yminsky** [comment]
@xclerc, can you take a look at this?

**Comment by xclerc** [comment]
I have created a pull request, because I am not completely sure
it is the best URL - see https://github.com/janestreet/bin_prot/pull/16.
