### ISSUE TITLE
bin_prot < v0.9.1 not compatible with jbuilder >= 1.0+beta12

### ISSUE THREAD

**Issue by agarwal** [janestreet/bin_prot#17]
jbuilder 1.0+beta12 removed support for `per_file`, which is being used in bin_prot until version v0.9.1. The opam files for bin_prot < v0.9.1 should thus constrain `jbuilder < 1.0+beta12`.

**Comment by hhugo** [comment]
I see the constraint in opam
https://github.com/ocaml/opam-repository/blob/master/packages/bin_prot/bin_prot.v0.9.0/opam#L13
