### ISSUE TITLE
xen subpackage is broken

### ISSUE THREAD

**Issue by samoht** [janestreet/bin_prot#19]
There are 2 issues in the packing of `bin_prot.xen`:

- `pkg-config` is not called with the right path. `ocb-stubblr` used to set `PKG_CONFIG_PATH` to `$(OPAM_LIB)/pkgconfig`. It is not the case anymore so `pkg-config` will just fail.
- The C code is not included in the package: there is no `c_names` in the `jbuild` file.

If you try to fix that, you hit a bug with jbuilder:

- `include` statement are always executed, even in optional stanza. Which means that normal builds fail on `pkg-config mirage-xen` when there is no `mirage-xen` package installed.

**Comment by samoht** [comment]
The jbuilder issue has been reported to https://github.com/ocaml/dune/issues/783

**Comment by jeremiedimino** [comment]
Hey @samoht, sorry this fell off our radar. We just setup a system to import github requests into iron, so moving forward we should be more reactive on these issues.

I notice that the linked issues have been closed, so I'm assuming that this is no longer an issue for you and I'm closing it. Feel free to reopen if it is still an issue.
