### ISSUE TITLE
Installation failure on FreeBSD

### ISSUE THREAD

**Issue by avysk** [janestreet/bin_prot#26]
See https://github.com/janestreet/bin_prot/blob/c29055692df839e3b10c776a78f7ba6ec4282e91/xen/cflags.sh#L1

`/bin/bash` does not exist on FreeBSD. If I install it from ports, it is `/usr/local/bin/bash`. The `ln -s /usr/local/bin/bash /bin/bash` workaround helps. Hardcoded paths are wrong.

**Comment by michaelzappa-jhuapl** [comment]
As well as on non-FHS Linux distributions.

**Comment by aalekseyev** [comment]
I'm changing it to run `/usr/bin/env bash` (on the internal repo, will make its way here eventually)

**Comment by hannesm** [comment]
While #29 has been merged, this still does not work. Would it be possible to have a release of bin_prot to support FreeBSD in the main opam-repository?
